@PhoneDirectory.Api_HostAddress = http://localhost:5224

GET {{PhoneDirectory.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{PhoneDirectory.Api_HostAddress}}/api/people
Accept: application/json

###

POST {{PhoneDirectory.Api_HostAddress}}/api/people
Content-Type: application/json

{
  "fullName": "Сидоров Алексей Сергеевич",
  "department": "IT",
  "phone": "+7 900 111-22-33",
  "email": "sidorov@example.com",
  "position": "Разработчик",
  "age": 28
}

###
POST {{PhoneDirectory.Api_HostAddress}}/api/people
Content-Type: application/json

{
  "fullName": "",
  "department": "",
  "phone": "+7 900 111-22-33",
  "email": "sidorov@example.com",
  "position": "Разработчик",
  "age": 28
}

###


DELETE {{PhoneDirectory.Api_HostAddress}}/api/people/3
Content-Type: application/json
###

GET {{PhoneDirectory.Api_HostAddress}}/api/people/search?name=Иван&department=IT
Content-Type: application/json

###


PUT {{PhoneDirectory.Api_HostAddress}}/api/people/3
Content-Type: application/json

{
  "fullName": "Сидоров Алексей Сергеевич",
  "department": "IT",
  "phone": "+7 999 111-22-33",
  "email": "sidorov@example.com",
  "position": "Senior Developer",
  "age": 29
}
###