@PhoneDirectory.Api_HostAddress = http://localhost:5224

GET {{PhoneDirectory.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{PhoneDirectory.Api_HostAddress}}/api/people/


###

GET {{PhoneDirectory.Api_HostAddress}}/api/people?page=0&pageSize=2

###

GET {{PhoneDirectory.Api_HostAddress}}/api/people?name=Петров

###

POST {{PhoneDirectory.Api_HostAddress}}/api/people
Content-Type: application/json

{
  "fullName": "Семенов1 Алексей Сергеевич",
  "department": "IT",
  "phone": "+7 900 111-22-33",
  "email": "semenov122@example.com",
  "position": "Разработчик",
  "age": 9
}

###
POST {{PhoneDirectory.Api_HostAddress}}/api/people
Content-Type: application/json

{
  "fullName": "   ",
  "department": "IT",
  "phone": "123",
  "email": "new@test.com",
  "position": "Developer",
  "age": 18
}

###


DELETE {{PhoneDirectory.Api_HostAddress}}/api/people/3
Content-Type: application/json
###

GET {{PhoneDirectory.Api_HostAddress}}/api/people/search?department=IT
Content-Type: application/json

###


PUT {{PhoneDirectory.Api_HostAddress}}/api/people/14
Content-Type: application/json

{
  "fullName": "Сидоров Алексей Сергеевич1",
  "department": "IT",
  "phone": "+7 999 111-22-33",
  "email": "sidorov@example.com",
  "position": "Senior Developer",
  "age": 29
}
###